[package]
edition = "2021"
name = "bevy_sprite_experiment"
version = "0.1.0"

[dependencies]
bevy = "0.13.0"
bevy-inspector-egui = "0.23.4"
bevy_editor_pls = "0.8.1"
bevy_rapier2d = "0.25.0"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "z"
